---
name: Pytest installed application

on:
  pull_request:
    branches:
      - main
      - v0.*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install .
      - name: Clear and recreate configs dir
        run: |
          sudo rm -rf /etc/ingestation
          sudo mkdir /etc/ingestation
          sudo chmod 0755 /etc/ingestation
      - name: Copy valid configs
        run: |
          sudo cp tests/configs/pytest/*.json /etc/ingestation/
      - name: Test with pytest
        run: |
          pytest
